version: "2"
services:
  server:
    image: notary:server-0.6.1-2
    container_name: notaryserver
    networks:
      mdb:
      sandbox:
        aliases:
          - notaryserver
    ports:
      - "8080"
      - "4443:4443"
    volumes:
      - ./notary:/notarydir
      - ./configs:/notaryconfigs
    entrypoint: /usr/bin/env sh
    command: -c "/notarydir/migrations/migrate.sh && notary-server -config=/notaryconfigs/server-config.json"
    depends_on:
      - signer

  signer:
    image: notary:signer-0.6.1-2
    container_name: notarysigner
    networks:
      mdb:
      sandbox:
        aliases:
          - notarysigner
    volumes:
      - ./notary:/notarydir
      - ./configs:/notaryconfigs
    entrypoint: /usr/bin/env sh
    command: -c "/notarydir/migrations/migrate.sh && notary-signer -config=/notaryconfigs/signer-config.json"

  trustsandbox-admin:
    image: docker:dind
    networks:
      - sandbox
    volumes:
      - ./notary:/notary
      - ./configs:/notaryconfigs
    privileged: true
    container_name: trustsandbox-admin
    depends_on:
      - registrysandbox
    environment:
      DOCKER_CONTENT_TRUST: 1
      DOCKER_CONTENT_TRUST_SERVER: https://notaryserver:4443
      NOTARY_ROOT_PASSPHRASE: root-passphrase
      NOTARY_TARGETS_PASSPHRASE: targets-passphrase
      NOTARY_SNAPSHOT_PASSPHRASE: snapshot-passphrase
    entrypoint: ""
    command: |-
        sh -c '
            cp /notary/fixtures/root-ca.crt /usr/local/share/ca-certificates/root-ca.crt &&
            update-ca-certificates &&
            wget https://github.com/notaryproject/notary/releases/download/v0.6.1/notary-Linux-amd64 -O /opt/notary &&
            chmod +x /opt/notary &&
            ln -s /opt/notary /usr/bin/notary &&
            echo "alias notary=\"notary -c /notaryconfigs/client-config.json\"" >> /etc/profile.d/alias.sh &&
            dockerd-entrypoint.sh --insecure-registry registry:5000'

  trustsandbox-delegate:
    image: docker:dind
    networks:
      - sandbox
    volumes:
      - ./notary:/notary
      - ./configs:/notaryconfigs
    privileged: true
    container_name: trustsandbox-delegate
    depends_on:
      - registrysandbox
    environment:
      DOCKER_CONTENT_TRUST: 1
      DOCKER_CONTENT_TRUST_SERVER: https://notaryserver:4443
    entrypoint: ""
    command: |-
        sh -c '
            cp /notary/fixtures/root-ca.crt /usr/local/share/ca-certificates/root-ca.crt &&
            update-ca-certificates &&
            dockerd-entrypoint.sh --insecure-registry registry:5000'

  registrysandbox:
    image: registry:2.7
    ports:
      - "5000:5000"
    networks:
      sandbox:
        aliases:
          - registry
    container_name: registrysandbox

networks:
  mdb:
    external: false
  sandbox:
    external: false
