version: "2"
services:
  server:
    image: notary:server-0.6.1-2
    container_name: notaryserver
    networks:
      sandbox:
        aliases:
          - notaryserver
    ports:
      - "4443:4443"
    depends_on:
      - signer
    volumes:
      - ./notary:/notarydir
    command: |-
      sh -c "/notarydir/migrations/migrate.sh &&
      cd /notarydir/fixtures &&
      notary-server -config=/notarydir/fixtures/server-config-local.json"

  signer:
    image: notary:signer-0.6.1-2
    container_name: notarysigner
    networks:
      sandbox:
        aliases:
          - notarysigner
    volumes:
      - ./notary:/notarydir
    command: |-
      sh -c "/notarydir/migrations/migrate.sh &&
      cd /notarydir/fixtures &&
      notary-signer -config=/notarydir/fixtures/signer-config-local.json"

  trustsandbox:
    image: docker:dind
    networks:
      - sandbox
    volumes:
      - ./notary:/notary
    privileged: true
    container_name: trustsandbox
    entrypoint: ""
    command: |-
        sh -c '
            cp /notary/fixtures/root-ca.crt /usr/local/share/ca-certificates/root-ca.crt &&
            update-ca-certificates &&
            dockerd-entrypoint.sh --insecure-registry sandboxregistry:5000'

  sandboxregistry:
    image: registry:2.7
    ports:
      - "5000:5000"
    networks:
      sandbox:
        aliases:
          - sandboxregistry
    container_name: sandboxregistry

networks:
  sandbox:
    external: false

